<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDhi89Mo\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDhi89Mo/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDhi89Mo.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDhi89Mo\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDhi89Mo\App_KernelProdContainer([
    'container.build_hash' => 'Dhi89Mo',
    'container.build_id' => '93b577d3',
    'container.build_time' => 1745580738,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDhi89Mo');
