<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get2faSuccessService extends App_KernelProdContainer
{
    /*
     * Gets the public '2fa_success' shared autowired service.
     *
     * @return \App\Security\TwoFactor\TwoFactorAuthenticationSuccessHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'TwoFactor'.\DIRECTORY_SEPARATOR.'TwoFactorAuthenticationSuccessHandler.php';

        $a = ($container->privates['App\\Authentication\\LegacyHandler\\Authentication'] ?? $container->load('getAuthenticationService'));

        if (isset($container->services['2fa_success'])) {
            return $container->services['2fa_success'];
        }

        return $container->services['2fa_success'] = new \App\Security\TwoFactor\TwoFactorAuthenticationSuccessHandler($a);
    }
}
