<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ShivasVersioning_Command_Status_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.shivas_versioning.command.status.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.shivas_versioning.command.status.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:version:status', [], 'Show current application version status', false, #[\Closure(name: 'shivas_versioning.command.status', class: 'Shivas\\VersioningBundle\\Command\\StatusCommand')] fn (): \Shivas\VersioningBundle\Command\StatusCommand => ($container->privates['shivas_versioning.command.status'] ?? $container->load('getShivasVersioning_Command_StatusService')));
    }
}
