<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppStringsStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Languages\DataProvider\AppStringsStateProvider' shared autowired service.
     *
     * @return \App\Languages\DataProvider\AppStringsStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Languages'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'AppStringsStateProvider.php';

        return $container->privates['App\\Languages\\DataProvider\\AppStringsStateProvider'] = new \App\Languages\DataProvider\AppStringsStateProvider(($container->privates['App\\Languages\\LegacyHandler\\AppStringsHandler'] ?? $container->load('getAppStringsHandlerService')));
    }
}
