<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthArgumentResolverService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Nbgrp\OneloginSamlBundle\Onelogin\AuthArgumentResolver' shared service.
     *
     * @return \Nbgrp\OneloginSamlBundle\Onelogin\AuthArgumentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nbgrp'.\DIRECTORY_SEPARATOR.'onelogin-saml-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Onelogin'.\DIRECTORY_SEPARATOR.'AuthArgumentResolver.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nbgrp'.\DIRECTORY_SEPARATOR.'onelogin-saml-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Idp'.\DIRECTORY_SEPARATOR.'IdpResolverInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nbgrp'.\DIRECTORY_SEPARATOR.'onelogin-saml-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Idp'.\DIRECTORY_SEPARATOR.'IdpResolver.php';

        return $container->privates['Nbgrp\\OneloginSamlBundle\\Onelogin\\AuthArgumentResolver'] = new \Nbgrp\OneloginSamlBundle\Onelogin\AuthArgumentResolver(($container->privates['Nbgrp\\OneloginSamlBundle\\Onelogin\\AuthRegistryInterface'] ?? $container->load('getAuthRegistryInterfaceService')), ($container->privates['Nbgrp\\OneloginSamlBundle\\Idp\\IdpResolverInterface'] ??= new \Nbgrp\OneloginSamlBundle\Idp\IdpResolver('idp')));
    }
}
