<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseLoggingEnvVarProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Logging\Services\BaseLoggingEnvVarProcessor' shared autowired service.
     *
     * @return \App\Logging\Services\BaseLoggingEnvVarProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'dependency-injection'.\DIRECTORY_SEPARATOR.'EnvVarProcessorInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Logging'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'BaseLoggingEnvVarProcessor.php';

        return $container->privates['App\\Logging\\Services\\BaseLoggingEnvVarProcessor'] = new \App\Logging\Services\BaseLoggingEnvVarProcessor(\dirname(__DIR__, 3));
    }
}
