<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionAssetCopyCacheWarmerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Engine\Service\Extensions\ExtensionAssetCopyCacheWarmer' shared autowired service.
     *
     * @return \App\Engine\Service\Extensions\ExtensionAssetCopyCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'CacheWarmer'.\DIRECTORY_SEPARATOR.'CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Extensions'.\DIRECTORY_SEPARATOR.'ExtensionAssetCopyCacheWarmer.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Extensions'.\DIRECTORY_SEPARATOR.'ExtensionAssetCopyInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Extensions'.\DIRECTORY_SEPARATOR.'ExtensionAssetCopy.php';

        return $container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopyCacheWarmer'] = new \App\Engine\Service\Extensions\ExtensionAssetCopyCacheWarmer(($container->privates['App\\Engine\\Service\\Extensions\\ExtensionAssetCopy'] ??= new \App\Engine\Service\Extensions\ExtensionAssetCopy(\dirname(__DIR__, 3))));
    }
}
