<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordListStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Data\DataProvider\RecordListStateProvider' shared autowired service.
     *
     * @return \App\Data\DataProvider\RecordListStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Data'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'RecordListStateProvider.php';

        return $container->privates['App\\Data\\DataProvider\\RecordListStateProvider'] = new \App\Data\DataProvider\RecordListStateProvider(($container->privates['App\\Data\\LegacyHandler\\RecordListHandler'] ?? $container->load('getRecordListHandlerService')), ($container->privates['App\\Data\\Service\\Record\\ApiRecordMappers\\ApiRecordMapperRunner'] ?? $container->load('getApiRecordMapperRunnerService')));
    }
}
