<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecentlyViewedHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Module\LegacyHandler\RecentlyViewed\RecentlyViewedHandler' shared autowired service.
     *
     * @return \App\Module\LegacyHandler\RecentlyViewed\RecentlyViewedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Module'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'RecentlyViewed'.\DIRECTORY_SEPARATOR.'RecentlyViewedHandler.php';

        return $container->privates['App\\Module\\LegacyHandler\\RecentlyViewed\\RecentlyViewedHandler'] = new \App\Module\LegacyHandler\RecentlyViewed\RecentlyViewedHandler(\dirname(__DIR__, 3), (\dirname(__DIR__, 3).'/public/legacy'), 'SCRMSESSID', 'SCRMSESSID', $container->parameters['ui'], ($container->privates['App\\Engine\\LegacyHandler\\LegacyScopeState'] ??= new \App\Engine\LegacyHandler\LegacyScopeState()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? self::getModuleNameMapperHandlerService($container)));
    }
}
