<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchDefsNumberTypeMapperService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ViewDefinitions\LegacyHandler\SearchDefs\SearchDefsNumberTypeMapper' shared autowired service.
     *
     * @return \App\ViewDefinitions\LegacyHandler\SearchDefs\SearchDefsNumberTypeMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'ViewDefinitionMapperInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'SearchDefs'.\DIRECTORY_SEPARATOR.'SearchDefsNumberTypeMapper.php';

        return $container->privates['App\\ViewDefinitions\\LegacyHandler\\SearchDefs\\SearchDefsNumberTypeMapper'] = new \App\ViewDefinitions\LegacyHandler\SearchDefs\SearchDefsNumberTypeMapper(($container->services['app.system-configs'] ?? $container->load('getApp_SystemconfigsService')));
    }
}
