<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatisticsStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Statistics\DataProvider\StatisticsStateProvider' shared autowired service.
     *
     * @return \App\Statistics\DataProvider\StatisticsStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Statistics'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'StatisticsStateProvider.php';

        return $container->privates['App\\Statistics\\DataProvider\\StatisticsStateProvider'] = new \App\Statistics\DataProvider\StatisticsStateProvider(($container->privates['App\\Statistics\\Service\\StatisticsProviderRegistry'] ?? $container->load('getStatisticsProviderRegistryService')));
    }
}
