<?php

namespace ContainerDhi89Mo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeImagesStateProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Themes\DataProvider\ThemeImagesStateProvider' shared autowired service.
     *
     * @return \App\Themes\DataProvider\ThemeImagesStateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Themes'.\DIRECTORY_SEPARATOR.'DataProvider'.\DIRECTORY_SEPARATOR.'ThemeImagesStateProvider.php';

        return $container->privates['App\\Themes\\DataProvider\\ThemeImagesStateProvider'] = new \App\Themes\DataProvider\ThemeImagesStateProvider(($container->privates['App\\Themes\\Service\\ThemeImageService'] ?? $container->load('getThemeImageServiceService')));
    }
}
